### ISSUE TITLE
Read override files.

### ISSUE THREAD

**Issue by osterrfr-crim** [pmsipilot/docker-compose-viz#16]
Would be nice if the parsing of the yml took into account the override.yml as well.

**Comment by jubianchi** [comment]
@osterrfr-crim I just pushed a PR with this feature implemented.

Please could you give it a try by using the docker image (`pmsipilot/docker-compose-viz:docker-compose-override`)  or the PR branch (`docker-compose-override`) ?

**Comment by osterrfr-crim** [comment]
Quick response time ! Thanks.

**Comment by osterrfr-crim** [comment]
Though in my case this seems to only read the sections in the override now instead of the union of docker-compose.yml and docker-compose.override.yml ... In other words we lose the info in the docker-compose.yml file...

**Comment by jubianchi** [comment]
@osterrfr-crim I just went through the `docker-compose` documentation and it seems my implementation is too weak.

It only handles `override` file. I have to change some code to handle any override (for example `docker-compose.prod.yml`)

Let me check the code to resolve the problem you have.

**Comment by jubianchi** [comment]
@osterrfr-crim Here is what I have and what I get:

### `docker-compose.yml`

```yml
app:
    image: node:8.1
    environment:
        POSTGRES_USER: app
        POSTGRES_PASSWORD:
        POSTGRES_DB: app
    links:
        - db:db

db:
    image: postgres:9.6
    environment:
        POSTGRES_USER: app
        POSTGRES_PASSWORD:
        POSTGRES_DB: app

```

### `docker-compose.override.yml`

```yml
app:
    environment:
        POSTGRES_PASSWORD: foo
    ports:
        - 42:42

db:
    environment:
        POSTGRES_PASSWORD: foo
    volumes:
        - ./db/prod.sql:/docker-entrypoint-initdb.d/init.sql
```

### `docker-compose.png`

![docker-compose](https://user-images.githubusercontent.com/327237/27151884-4b5a647e-514c-11e7-9313-864254171532.png)

The resulting graph does not seem to miss something.
