### ISSUE TITLE
Wrong display of ports

### ISSUE THREAD

**Issue by Braintelligence** [pmsipilot/docker-compose-viz#30]
Hey there,

if docker-compose looks like this:

```
ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
```

Then the created image shows 0 as port instead of 80.

**Comment by alexanderkjeldaas** [comment]
I'm getting the ports, but they are labels coming from "0":

![docker-compose](https://user-images.githubusercontent.com/339369/35723156-8e4c5fbc-07f9-11e8-9c56-f29d4511e04c.png)

**Comment by jubianchi** [comment]
@alexanderkjeldaas can you provide an example `docker-compose.yml` please ?

**Comment by alexanderkjeldaas** [comment]
```
version: '3.5'

services:

  test:
    networks:
      - test
    image: test
    ports:
      - "${TEST}:8888"

networks:
  test:
    external: true
```

of course in the above ${TEST} is unknown

this also produces the same output:

```
version: '3.5'

services:

  test:
    networks:
      - test
    image: test
    ports:
      - "0.0.0.0:80:8888"

networks:
  test:
    external: true
```
