### ISSUE TITLE
More detail on invalid YAML

### ISSUE THREAD

**Issue by Xenira** [pmsipilot/docker-compose-viz#33]
Expected behavior: When provided with invalid yaml file, point to line (and when possible column) of malformed yaml

Current behavior: 'File "%s" does not contain valid YAML' is thrown as a new InvalidArgumentException. (functions.php line 46)

The file I used passed a different yaml validator and works with compose (compose file version 3.2) but fails with this tool. Maybe a more detailed error message can help to resolve the problem.

**Comment by jubianchi** [comment]
Hi! Could you please provide an example yaml which reproduces the error.

Thanks!

**Comment by Xenira** [comment]
Sadly I am not at liberty to post the file here.
I will do some testing on my own regarding the issue with the format.
A more detailed error message or simply passing the original exception (I have no experience with php and the yaml library, so I could be off) should help everyone else with such an error.

**Comment by jubianchi** [comment]
@Xenira Thanks! I'm going to push a fix so you will be able to test and see if the error reporting is better.

**Comment by Xenira** [comment]
Nice, the exception is way better now. Thanks.

If its from interest, the problem was caused by a duplicate key. Normally I would expect the second key to override the first key.
In this example I would expect ```some-other-value``` to be used for ```deploy.some_config``` instead of ```some-value```:
```yaml
x-networking:
  &networking-reference
  deploy:
    some_config: some-value

services:
  service1:
    << : *networking-reference
    deploy:
      some_config: some-other-value
```
