### ISSUE TITLE
Volume long syntax referes to a single node 'named:'

### ISSUE THREAD

**Issue by Xenira** [pmsipilot/docker-compose-viz#36]
When using the long syntax for volumes, there is only one volume node generated with the label 'named:' (see screenshot), that is connected to every service using a volume with long syntax.
```yml
volumes:
  - type: bind
    source: /data/some_directory
    target: /some_directory
```
![image](https://user-images.githubusercontent.com/1288524/37037910-a3dc1962-2153-11e8-90b9-250d1848e67d.png)
