### ISSUE TITLE
YAML anchor  throws error

### ISSUE THREAD

**Issue by burnbabyburn** [pmsipilot/docker-compose-viz#61]
As @Xenira stated in #33 , the project has an issue if [compose extension fields](https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields) are used.
invalid example:
```
x-environment:
  &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

services:
  service1:
    environment:
      <<: *default-tz-puid-pgid
      Key0: Value0
...
```
valid example
```
x-environment:
  &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

services:
  service1:
    environment:
      <<: &default-tz-puid-pgid
      Key0: Value0
...
```

 The error thrown would be:
```
In functions.php line 41:

  File "docker-compose.yml" does not contain valid YAML


In Parser.php line 476:

  Unable to parse at line 21 (near "<< * default-tz-puid-pgid").
```

To me it looks like the filter/search value for the [yaml merge](https://yaml.org/type/merge.html) is not perfect.
If you change `<<: *networking-reference` to `<< : &networking-reference` no error is thrown but its not a valid yaml/compose-file anymore.
So the script is happy with defining a yaml anchor (&) but not using it (*)
[Further information on using yaml anchor in compose](https://www.cloudsavvyit.com/10765/how-to-simplify-docker-compose-files-with-yaml-anchors-and-extensions/)

Seems to be a Symfony error. So it seems we have to wait till docker-compose or symfony adjust.

**Comment by jubianchi** [comment]
Hi @burnbabyburn

There's a tiny issue in your YAML syntax, you should use anchors/references like that:

```yaml
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

services:
  service1:
    environment:
      <<: *default-tz-puid-pgid
      Key0: Value0
```

I'm closing this issue as the YAML parser is ok and everything seems fine with the right syntax. Feel free to reopen if needed.
